# Generated by Django 2.2.28 on 2025-03-10 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('calories', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('carbohydrate', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Meals',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('exercise_type', models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance')], default='Cardio', max_length=20)),
                ('duration', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Workouts',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('experience', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('goal', models.CharField(blank=True, choices=[('Lose weight', 'Lose weight'), ('Maintain weight', 'Maintain weight'), ('Gain weight', 'Gain weight')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sets', models.IntegerField(default=10)),
                ('reps', models.IntegerField(default=10)),
                ('workout', models.ManyToManyField(to='fitnessTracker.Workout')),
            ],
            options={
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='CalanderDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('year', models.IntegerField(default=2025)),
                ('day', models.IntegerField(default=1)),
                ('meals', models.ManyToManyField(to='fitnessTracker.Meal')),
                ('workouts', models.ManyToManyField(to='fitnessTracker.Workout')),
            ],
        ),
    ]
