# Generated by Django 2.1.5 on 2025-03-06 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitnessTracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name_plural': 'Exercises'},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='Exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance')], default='Cardio', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='fitnessTracker.Exercise'),
        ),
        migrations.AddField(
            model_name='day',
            name='exercises',
            field=models.ManyToManyField(to='fitnessTracker.Exercise'),
        ),
        migrations.AddField(
            model_name='day',
            name='meals',
            field=models.ManyToManyField(to='fitnessTracker.Meal'),
        ),
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
