# Generated by Django 2.1.5 on 2025-03-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessTracker', '0002_auto_20250306_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='day',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='day',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ManyToManyField(to='fitnessTracker.Workout'),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise_type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance')], default='Cardio', max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbohydrate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
