# Generated by Django 2.1.5 on 2025-03-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessTracker', '0002_auto_20250311_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourites',
            field=models.ManyToManyField(to='fitnessTracker.Workout'),
        ),
    ]
