# Generated by Django 2.1.5 on 2025-03-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessTracker', '0005_workout_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercise_type',
            field=models.CharField(choices=[('Cardio', 'Cardio'), ('Strength', 'Strength'), ('Flexibility', 'Flexibility'), ('Balance', 'Balance'), ('Chest', 'Chest'), ('Bicep', 'Bicep'), ('Tricep', 'Tricep'), ('Shoulder', 'Shoulder'), ('Forearm', 'Forearm'), ('Back', 'Back'), ('Legs', 'Legs'), ('Abs', 'Abs')], default='Cardio', max_length=20),
        ),
    ]
