# Generated by Django 2.1.5 on 2025-03-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessTracker', '0005_remove_exercise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
