# Generated by Django 2.1.5 on 2025-03-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessTracker', '0006_auto_20250306_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalanderDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('JANUARY', 'January'), ('FEBUARY', 'Febuary'), ('MARCH', 'March'), ('APRIl', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULY', 'July'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=20)),
                ('year', models.IntegerField(default=2025)),
                ('day', models.IntegerField(default=1)),
                ('meal', models.ManyToManyField(to='fitnessTracker.Meal')),
                ('workout', models.ManyToManyField(to='fitnessTracker.Workout')),
            ],
        ),
    ]
