# Generated by Django 2.1.5 on 2025-03-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessTracker', '0008_auto_20250307_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calanderdate',
            old_name='meal',
            new_name='meals',
        ),
        migrations.RenameField(
            model_name='calanderdate',
            old_name='workout',
            new_name='workouts',
        ),
    ]
