# Generated by Django 2.2.28 on 2025-03-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessTracker', '0009_auto_20250307_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calanderdate',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20),
        ),
    ]
